/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-19 23:59:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import eventPlanner.eventPlannerDBUtil;
import eventPlanner.Event;

public final class updateEvent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("eventPlanner.Event");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("eventPlanner.eventPlannerDBUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    int eventId = Integer.parseInt(request.getParameter("eventId"));
    Event event = null;

    // Fetch the event from the database
    try (Connection conn = eventPlannerDBUtil.getConnection();
         PreparedStatement stmt = conn.prepareStatement("SELECT * FROM event_planner WHERE event_id = ?")) {
        
        stmt.setInt(1, eventId);
        ResultSet rs = stmt.executeQuery();
        if (rs.next()) {
            event = new Event(
                rs.getInt("event_id"),
                rs.getString("event_type"),
                rs.getString("event_venue"),
                rs.getString("nop"),
                rs.getString("description"),
                rs.getString("event_image_path")
            );
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Update Event</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-image: url(\"images/background1.jpg\");\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .update-event-container {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.85);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            color: #2d3436;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: stretch;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            color: #2d3436;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"], input[type=\"number\"], textarea {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        textarea {\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            resize: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submit-btn {\r\n");
      out.write("            background-color: #00b894;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cancel-btn {\r\n");
      out.write("            background-color: #d63031;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            flex: 1;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        select {\r\n");
      out.write("		    padding: 10px;\r\n");
      out.write("		    border-radius: 10px;\r\n");
      out.write("		    border: 1px solid #ccc;\r\n");
      out.write("		    background-color: white;\r\n");
      out.write("		    font-size: 1rem;\r\n");
      out.write("		    color: #2d3436;\r\n");
      out.write("		    appearance: none; /* Remove default styling */\r\n");
      out.write("		    background-image: url('data:image/svg+xml;utf8,<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" fill=\"rgba(0,0,0,0.5)\" viewBox=\"0 0 16 16\"><path d=\"M1 4.5L8 11.5l7-7h-14z\"/></svg>'); /* Custom arrow */\r\n");
      out.write("		    background-repeat: no-repeat;\r\n");
      out.write("		    background-position: right 10px center; /* Position arrow */\r\n");
      out.write("		    background-size: 12px; /* Size of arrow */\r\n");
      out.write("		    transition: all 0.3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		select:focus {\r\n");
      out.write("		    border-color: #00b894; /* Change border color on focus */\r\n");
      out.write("		    outline: none; /* Remove default focus outline */\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		select option {\r\n");
      out.write("		    padding: 10px; /* Option padding */\r\n");
      out.write("		    background-color: white; /* Option background color */\r\n");
      out.write("		    color: #2d3436; /* Option text color */\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		select:hover {\r\n");
      out.write("		    border-color: #00b894; /* Change border color on hover */\r\n");
      out.write("		}\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"update-event-container\">\r\n");
      out.write("        <h2>Update Event</h2>\r\n");
      out.write("        <form action=\"updateEventServlet\" method=\"POST\" enctype=\"multipart/form-data\">\r\n");
      out.write("            <input type=\"hidden\" name=\"event_id\" value=\"");
      out.print( event.getEventId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("            <label for=\"event_type\">Event Type:</label>\r\n");
      out.write("            <select id=\"event_type\" name=\"event_type\" required>\r\n");
      out.write("                <option value=\"");
      out.print( event.getEventType() );
      out.write("\" selected>");
      out.print( event.getEventType() );
      out.write("</option>\r\n");
      out.write("                <option value=\"wedding\">Wedding</option>\r\n");
      out.write("                <option value=\"birthday_party\">Birthday Party</option>\r\n");
      out.write("                <option value=\"corporate_event\">Corporate Event</option>\r\n");
      out.write("                <option value=\"anniversary_celebration\">Anniversary Celebration</option>\r\n");
      out.write("                <option value=\"baby_shower\">Baby Shower</option>\r\n");
      out.write("                <option value=\"graduation_party\">Graduation Party</option>\r\n");
      out.write("                <option value=\"concert\">Concert</option>\r\n");
      out.write("                <option value=\"charity_event\">Charity Event</option>\r\n");
      out.write("                <option value=\"family_reunion\">Family Reunion</option>\r\n");
      out.write("                <option value=\"holiday_party\">Holiday Party</option>\r\n");
      out.write("                <option value=\"conference\">Conference</option>\r\n");
      out.write("                <option value=\"seminar\">Seminar</option>\r\n");
      out.write("                <option value=\"workshop\">Workshop</option>\r\n");
      out.write("                <option value=\"prom\">Prom</option>\r\n");
      out.write("                <option value=\"sporting_event\">Sporting Event</option>\r\n");
      out.write("                <option value=\"picnic\">Picnic</option>\r\n");
      out.write("                <option value=\"themed_party\">Themed Party</option>\r\n");
      out.write("                <option value=\"farewell_party\">Farewell Party</option>\r\n");
      out.write("                <option value=\"art_exhibition\">Art Exhibition</option>\r\n");
      out.write("                <option value=\"fashion_show\">Fashion Show</option>\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"event_venue\">Event Venue:</label>\r\n");
      out.write("            <input type=\"text\" id=\"event_venue\" name=\"event_venue\" value=\"");
      out.print( event.getEventVenue() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"nop\">Number of Participants:</label>\r\n");
      out.write("            <input type=\"number\" id=\"nop\" name=\"nop\" value=\"");
      out.print( event.getNop() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"event_description\">Event Description:</label>\r\n");
      out.write("            <textarea id=\"event_description\" name=\"event_description\" required>");
      out.print( event.getDescription() );
      out.write("</textarea>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"event_image\">Event Image (optional):</label>\r\n");
      out.write("            <input type=\"file\" id=\"event_image\" name=\"event_image\" accept=\"image/*\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"btn-container\">\r\n");
      out.write("                <button type=\"submit\" class=\"submit-btn\">Update</button>\r\n");
      out.write("                <a href=\"EventPage.jsp\" class=\"cancel-btn\">Cancel</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
